from __future__ import annotations

from first_agentic.domain.contracts import CoderOutput
from first_agentic.domain.models import Task
from first_agentic.repo.adapter import RepoAdapter


class SandboxCoderAgent:
    def implement(self, task: Task, repo: RepoAdapter) -> CoderOutput:
        safe_title = task.request.title.lower().replace(" ", "_")
        target_root = task.request.target_paths[0] if task.request.target_paths else "docs/sandbox"
        target_file = f"{target_root.rstrip('/')}/{task.task_id.lower()}_{safe_title}.md"

        content = "\n".join(
            [
                f"# Sandbox Task {task.task_id}",
                "",
                f"title: {task.request.title}",
                f"description: {task.request.description}",
                f"review_round: {task.review_round}",
                "",
                "This file is generated by SandboxCoderAgent to validate controlled repo changes.",
            ]
        )

        written_file = repo.write_file(target_file, content)
        return CoderOutput(
            summary="Sandbox code generation completed with controlled file changes.",
            changed_files=[written_file],
            notes=["Generated markdown artifact in allowed path."],
        )
